* Emacs initialization and package configuration

This is my emacs initialization and package configuration code that I have attemped to develop from a clean slate borrowing heavily from initialization code of numerous users. I have been an Emacs users for close to two decades and reasonably comfortable with Emacs and Elisp internals. Over the years I have been flitting between different configuration systems such as prelude, spacemacs, doom, radian etc. However, I found myself unable to fully grasp which feature came about from which package and how to go about precisely configuring the individual packages to my taste, no to mention, how to shed unwanted bloat and layers of abstraction introduced by the configuration management system itself. Perhaps I wasn't smart enough to really understand the enhancements, tuning and power tools provided by such advanced configuration management systems and never got around to master any one system. True to the spirit that the task of configuring Emacs to one's desire is never fully attained, the journey itself being the reward, I decided to just amalgamate code pieces from anyone's emacs configurations available for perusing and keep the abstraction to the bare bones and simply instantiate each feature as close to the author's recommendation as possible. Doing so, helped me understand the exact functionality provided by each feature and how to tap into it to improve the productivity of my workflow. After all a dish is more enjoyable if one makes it with the ingredients and recipes from renowned chefs than by simply ordering it from a menu.

I use a self-built OLKB (ortholinear mechanical keyboard) derived from the Sofle design and ofcourse customized to my unique taste. I also recently discovered a user-space app called kmonad which intercepts keystrokes between the kernel and user-layer apps interface and allow one to map even traditional keyboards (laptop builtins or traditional standalone PC) to almost qmk-like features. Here are the key customizations I would like the reader to be aware about so that they can understand the context/logic behind by emacs key bindings
- uses US English Dvorak layout
- modifier keys are multiplexed onto home row keys (both hands)
- to avoid pinky-RSI, the home row keys are maximally shifted to the outer columns. So, the inner most column is used for special keys such as tab, esc, bspc and del. So, the index finger does job of spanning keys of the innermost threee columns
- modifiers-on-homerow help me map the entire keyset on a single layer with only 50 keys (24L, 24R, space, return) and one additional layer for arrow and function keys
- with GUI-Lt/Rt (interpreted by emacs as super) available on the home row, it opens up the super based key bindings (eg s-c, s-v, s-s for copy, paste and save)
  
